- Makefile
gomonkey does not support arm arch, and marvell armhf pipeline is using arm arch.
Do not generate server.test for armhf.
I have used marvell_armhf pipeline to build sonic image.
> Workaround gomonkey for armhf

- sonic_data_client/events_client.go
The go routines don't get a formal exit, that breaks proper client disconnect from eventd.
Add the go routines into waitgroup and invoke done upon proper exit.
Via logs is the easy way.
Start a gnmi client and stop. Note in telemetry log the spew from go routines for proper exit.
> Events client: Ensure all go routines exit upon client disconnect.

- Makefile
- gnmi_server/constants.go
- gnmi_server/constants_readwrite.go
- gnmi_server/server.go
- gnmi_server/server_test.go
- telemetry/telemetry.go
PR for sonic-buildimage
https://github.com/sonic-net/sonic-buildimage/pull/11780
I will add a future env var ENABLE_NATIVE_WRITE which is another kind of gnmi write mode.
So, I need to rename TELEMETRY_WRITABLE and READ_WRITE_MODE to avoid conflict.
Rename compile env var and build tag.
Run unit test for sonic-gnmi.
> Rename compile env name for gnmi write

- Makefile
- patches/0001-Updated-to-filter-and-write-to-file.patch
- sonic_data_client/events_client.go
To make the tool usable in scripting environment
When configured via args:
- Write responses only to a o/p file instead of stdout.
- For on change events, filter for a specific event.
- Exit upon receiving N responses.
- Exit upon timeout.
The above would help use gnmi_cli as tool in scripting environment that does testing.
**Sample Usage:**
To receive any/all event until killed:
`gnmi_cli -client_types=gnmi -a 127.0.0.1:50051 -t EVENTS   -logtostderr -insecure -v 7 -qt s -q all[heartbeat=5] -streaming_type ON_CHANGE
`
To receive events to a file:
Add "`-output_file=<file>`"
To filter out for specific event:
Add "`-expected_event=<event module:event tag>`"
e.g. "`-expected_event=sonic-events-bgp:bgp-state`"
To read N events and exit
Add "`-expected_count <N>`"
To run with a max timeout: …
> gnmi_cli - Tool updte

- sonic_data_client/events_client.go
When client conn closes, returning due to queue error in event_send will not allow event_deinit_sub to occur, which will not stop hearbeat/start cache
Change return to break
> Fix heartbeat not stopping after client closes

- azure-pipelines.yml
GNMI native write needs to use bullseye as build environment.
Upgrade pipeline to use bullseye.
PR checker should pass.
> Upgrade pipeline to use bullseye.

- Makefile
- common_utils/context.go
- common_utils/shareMem.go
- gnmi_dump/gnmi_dump.go
- gnmi_server/server.go
- gnmi_server/server_test.go
Add tool for debug and unit test.
Use share memory to support counters.
Move check for EnableTranslibWrite to beginning of Set(). This change will simplify the logic for gnmi set fail, and no need to authenticate when EnableTranslibWrite  is false. 
Build image and run unit test.
> Add gnmi_dump tool for debug and unit test

- doc/grpc_telemetry.md
- proto/sonic.pb.go
- proto/sonic.proto
- testdata/database_config.json
- testdata/database_config_asic0.json
This PR is part of the following HLD:
Persistent loglevel HLD: https://github.com/sonic-net/SONiC/pull/1041
After the Logger tables moved from the LOGLEVEL_DB to the CONFIG_DB and the jinja2_cache was deleted the LOGLEVEL_DB is not in use.
Removed the LOGLEVEL_DB from the SONiC code
All tests were passed
> Remove LOGLEVEL DB since is no longer used

- telemetry/telemetry.go
var cfg was declared in line 62. Otherwise, the configuration will be abnormal.
var cfg was declared in line 62. Otherwise, the configuration will be abnormal.
var cfg was declared in line 62. Otherwise, the configuration will be abnormal.
> Fix the cfg variable configuration bug.

- gnmi_server/server_test.go
- sonic_data_client/non_db_client.go
Fix crash in which there was a divide by zero error inside retrieving cpu utilization
`Dec   1 04:31:03 PHX70-0101-0719-14T1 telemetry#/supervisord: telemetry   #011/sonic/src/sonic-telemetry/sonic_data_client/non_db_client.go:139 +0x99`
`Dec   1 04:31:03 PHX70-0101-0719-14T1 telemetry#/supervisord: telemetry   github.com/Azure/sonic-telemetry/sonic_data_client.getCpuUtil`
`Dec   1 04:31:03 PHX70-0101-0719-14T1 telemetry#/supervisord: telemetry   #011/sonic/src/sonic-telemetry/sonic_data_client/non_db_client.go:221 +0x34`
`Dec   1 04:31:03 PHX70-0101-0719-14T1 telemetry#/supervisord: telemetry   (0xc000000006, 0xc002e0ae00, 0x1, 0x1, 0x0)`
`Dec   1 04:31:03 PHX70-0101-0719-14T1 telemetry#/supervisord: telemetry   github.com/Azure/sonic-telemetry/sonic_data_client.getCpuUtilStat(0x0)`
`Dec …
> Fix crash when retrieving cpu utilization

- azure-pipelines.yml
Publish code coverage results
Modify azure pipeline yml file to install net core and publish code coverage results via Cobertura
Check code coverage
> [202012] Add net core and publish code coverage results

- azure-pipelines.yml
- telemetry/telemetry.go
Add additional logs for when there is a mismatching public key and private key such as timestamp and md5 checksum
Add logs
> Add logs for md5 checksum

- gnmi_server/server_test.go
- go.mod
- sonic_data_client/non_db_client.go
Fix crash in which there was a divide by zero error inside retrieving cpu utilization
Cherry pick https://github.com/sonic-net/sonic-gnmi/commit/a792474c9ab6a849aa2d935d7c10e49211e0b61d
Add code change to 202012 branch
Cherry pick commit
> [202012] Fix crash when retrieving cpu utilization

- gnmi_server/client_subscribe.go
- gnmi_server/connection_manager.go
- gnmi_server/server.go
- gnmi_server/server_test.go
- telemetry/telemetry.go
Incident in which client kept creating connections resulting in memory utilization alert
Implemented threshold feature such that there is a total amount of 100 connections allowed and no more.
End to end test/UT
> Limit client connections connecting to gnmi server

- Makefile
- go.mod
Go before 1.15.13 and 1.16.x before 1.16.5 has functions for DNS lookups that do not validate replies from DNS servers, and thus a return value may contain an unsafe injection (e.g., XSS) that does not conform to the RFC1035 format. Now 1.15.15 is used in sonic-slave-bullseye thus it's safe, this change is to update go.mod for align dependency with build version meanwhile.
Update go.mod align with golang compiler used by sonic-slave-bullseye docker.
unit test to do sanity check.
Add golang version check in gnmi build process to make sure no security concern later, for CVE-2021-33195
> Update go.mod version for telemetry build to align with sonic-slave-bullseye

- Makefile
- gnmi_server/server_test.go
Enable golang race detector in telemetry repo.
This PR included all the tests with "-race" enabled except gnmi_server and dial_out_client case.
Always run outer loop tests with "-race" enabled
Use unit test.
> Enable "-race" option for telemetry repo testing patch-1

- gnmi_server/server.go
- gnmi_server/server_test.go
- telemetry/telemetry.go
In integration test, we have a gnmi client running in PTF docker that is creating 5000 consecutive subscribe requests, sample mode, in which after receiving a single update, the client is no longer making rPC requests. The connection is still alive on the server-side and you can see below the top 3 goroutines balloon up all the way to ~1784 alive connections, which causes a high memory utilization alert inside the telemetry container. 
Inside sonic-gnmi code, I tested with simple http server that profiles the current process using pprof. Pprof will capture state of the process every few seconds (heap size, alloc, goroutine, etc). From the beginning of the process, when there were fewer client connections, we could see the top 3 connections at around ~500, but near the end see that it goes …
> Add keep alive policies to close idle client connections

- gnmi_server/client_subscribe.go
- gnmi_server/connection_manager.go
- gnmi_server/server_test.go
Bug in which connection manager is reset once being initialized and also improve UT
Accept 2 connections, reject third
Code fix
UT
> Fix bug in consecutive client connections

- sonic_db_config/db_config.go
- sonic_db_config/db_config_test.go
- tools/test/env.sh
- tools/test/get.sh
- tools/test/set.sh
- tools/test/subscribe.sh
- tools/test/telemetry.sh
Requires https://github.com/sonic-net/sonic-mgmt-common/pull/69
Most of the gNMI functionalities can be verified on any development server by running redis, telemetry server, and clients locally. Helps quick testing/debugging of changes before preparing the full build..
1) Added wrapper scripts to launch the server and client binaries from build/bin directory. These scripts prepare necessary environment (as required by translib) and fill default arguments whenever possible.. These scripts are not packaged in the docker image.
2) Enhanced the db_config parser to allow overriding database_config.json path through an env variable DB_CONFIG_PATH (same as the translib test tools). This helps running test tools on shared servers, where default paths are not accessible. Test server launcher …
> Test tools for running telemetry servers and clients locally

- Makefile
- transl_utils/ygot_diff.go
- transl_utils/ygot_diff_bench_test.go
- transl_utils/ygot_diff_test.go
Subscription enhancements proposed in https://github.com/sonic-net/SONiC/pull/1287 requires gNMI server to create a SAMPLE notification message by comparing YGOT objects from two successive iterations. We observed that the standard `ygot.Diff` API takes more time and memory when the YGOT objects have multiple child objects. Hence developed an in-house diff API
Performance issues of `ygot.Diff` API are mainly due to it flattening the YGOT objects into list of {leaf_path, leaf_value} pairs and then comparing those lists. The in-house `Diff` API avoids this flattening step. It traverses both YGOT object attributes together, compares the values inline and records the changes if any. Following table captures the time taken (in nanoseconds) by `ygot.Diff` and the in-house diff APIs for diffing …
> Ygot diff tool

- Makefile
- gnmi_server/server_test.go
- sonic_data_client/db_client.go
- sonic_data_client/events_client.go
Enable golang race detector in telemetry repo.
This PR included gnmi_server test with "-race" enabled and necessary fix.
Always run outer loop tests with "-race" enabled
Use unit test.
> Enable "-race" option for telemetry repo testing patch-2

- azure-pipelines.yml
Build for 202205 still not working correctly
- Corrected container to build in; bullseye instead of buster
- Correct resource endpoint for sonic-mgmt-common; sonic-net instead of Azure
- Correct .NET CORE pkg version to install; 11 instead of 10
MSFT ADO: 23062915
Modify azp file
Pipeline
> [202205] Correct changes in 202205 azp file

- sonic_data_client/db_client.go
Backport 399aea73f4c0bfbb3cf0daf9db5b41d27598c80c
git cherry-pick
pipeline
> [202012] Backport "Change log level" to stop excessive ticker and counter logs

- gnmi_server/server_test.go
- sonic_data_client/events_client.go
Streaming events was not working due to incomplete fix for race condition brought in PR #100
Fix was not completed in last PR; issues:
1) Mutex Unlock was not being called as it was using defer statement inside a continuous for loop which was blocking all other go routines from accessing.
2) Mutex Lock was being used incorrectly as it should be only for when resource is being read not written to. Use RWMutex and RLock for writing to resource
1) Added fix so that -race condition works and also "re enabled event client UT"
2) Added additional UT case for when events are dropped.
UT and pipeline
> Fix threading issues in Event Client

- Makefile
- azure-pipelines.yml
- gnmi_server/client_subscribe.go
- gnmi_server/server_test.go
- sonic_data_client/transl_data_client.go
- tools/test/env.sh
- transl_utils/transl_utils.go
gNMI specification allows the clients to use both fully qualified and bare yang paths. It also allows omitting wildcard keys. But all translib APIs expect fully qualified yang paths, with wildcard keys explicitly set. Server is expected to set the missing module prefixes and wildcard keys.
Today telemetry server directly passes the paths from the request to translib APIs. Hence it works only if the client uses fully qualified paths.
Part of the gNMI subscription enhancements discussed in HLD https://github.com/sonic-net/SONiC/pull/1287
Enhanced the TranslClient to use the PathValidator utility to preprocess get, set and subscribe request paths before calling translib APIs. PathValidator is setup to performs following actions:
* Verify the get/set/subscribe paths are known to translib
* …
> TranslClient: use PathValidator to sanitize the request paths

- azure-pipelines.yml
Pipeline was always using latest from sonic-mgmt-common master branch for compilation. It can fail whenever there is a major change in sonic-mgmt-common.
Updated the pipeline build step to checkout specific version of sonic-mgmt-common that would have been used by the 202205 image build. There is no 202205 branch in sonic-mgmt-common repo, hence hardcoding the commit id from the sonic-buildimage's submodule.
Pipeline build
> [202205] Fix sonic-mgmt-common version to ec32690 in pipeline

- Makefile
- azure-pipelines.yml
Pipeline was always using latest from sonic-mgmt-common master branch for compilation. It can fail whenever there is a major change in sonic-mgmt-common.
Updated the pipeline build step to checkout 202012 branch of sonic-mgmt-common
Pipeline build
> [202012] Fix sonic-mgmt-common version in pipeline build

- gnmi_server/server_test.go
- go.mod
- sonic_data_client/non_db_client.go
Fix crash in which there was a divide by zero error inside retrieving cpu utilization
ADO #16818227
Backport b93c4acbc4c8fdbd4f8fd0b3ae20d53425eeceb9 -> divide by zero
git cherry-pick
pipeline
> [202205] Backport "Fix crash when retrieving cpu utilization"

- Makefile
If --enable-dialout is presented and set as --enable-dialout=0, dialout part code will be deprecated, which should be used in internal branch. Otherwise dialout code should be contained as before.
dialout part code will be deprecated in internal usage, thus we need add some build flag to control it.
Add build flag into gnmi as --enable-dialout.
If --enable-dialout is presented and set as --enable-dialout=0, dialout part code will be deprecated, which should be used in internal branch.
Otherwise dialout code should be contained as before.
local build
> Add build flag into gnmi as --enable-dialout.

- .github/workflows/semgrep.yml
- azure-pipelines.yml
Pipeline is always fetching latest of sonic-mgmt-common and sonic-swss-common repos for its builds. They must be use source code from 202305 branch
Checkout latest from `$(System.PullRequest.TargetBranch)` during PR builds and from `$(Build.SourceBranchName)` during manual builds.
Known issue: other pipeline artefacts are still being downloaded from master branch. Not a blocker as of now.
Pipeline build
> [202305] Checkout correct branch from sonic-mgmt-common and sonic-swss-common during pipeline build

- swsscommon/Makefile
Why I did it
Telemetry service crashed on armhf platform.
How I did it
Update makefile, and armhf is 32-bit.
How to verify it
Install new image on armhf platform, and telemetry service should be fine.
> Update makefile to support armhf (#132)

- azure-pipelines.yml
sonic-gnmi pipeline breaks with error: "System.IO.IOException: No space left on device : '/home/vsts/agents/3.220.5/_diag/Worker_20230719-220457-utc.log'"
Only install necessary bullseye debs instead of entire artifact
Pipeline
> Install necessary debs instead of entire artifact in azp

- gnmi_server/server.go
- sonic_data_client/client_test.go
- sonic_data_client/mixed_db_client.go
- telemetry/telemetry.go
Integrate ZMQ to GNMI to improve Dash GNMI API performance. 
Currently Dash gnmi to orchagent communitcation using redis based channel, switch to ZMQ based change will improve performance. 
Integrate ZMQ to gnmi service.
Manually test.
Add new UT.
Microsoft ADO (number only): 17753835
Integrate ZMQ to GNMI to improve Dash GNMI API performance.
> Integrate ZMQ to GNMI to improve Dash GNMI API performance. 

- sonic_data_client/mixed_db_client.go
- test/test_gnmi_appldb.py
protobytes is empty for default value, and GNMI needs to support this scenario.
If both json and proto are empty, use empty protobytes.
> Support empty protobytes

- gnmi_server/server_test.go
- sonic_data_client/mixed_db_client.go
- test/test_gnmi_appldb.py
- test/test_gnmi_configdb.py
- test/test_gnmi_countersdb.py
- testdata/CONFIG_DHCP_SERVER.txt
Need to read full config for SONiC
Read CONFIG DB and convert to json.
Verified with unit test and end2end test.
> Read full config with gnmi get

- Makefile
- proto/sonic_internal.proto
PR #139 introduced a syntax error in sonic_internal.proto file. Looks like sonic_internal.pb.go was manually updated and not re-generated from the proto file. Hence the syntax error went unnoticed.
Now sonic_internal.pb.go re-generation is getting triggered randomly in some clones during docker build causing build failure. This build includes a make target that compiles gotest binary for *gnmi_server* package. All go files are prerequisites for this target. This triggers sonic_internal.pb.go target if sonic_internal.proto got a higher timestamp than sonic_internal.pb.go during git clone. Hence the random failure.
This gotest binary is never used now. Pipeline builds run the go tests directly on source packages. Hence we can remove this makefile target.
* Fixed the syntax error in "delete" …
> Fix random build failures due to syntax error in sonic_internal.proto

- gnmi_server/server_test.go
- testdata/NEIGH_STATE_TABLE.txt
On change mode backport PR requires changes to prepareStateDb(), mainly loading data set NEIGH_STATE_TABLE, as our UT is based off that data set.
Backport certain needed changes from another PR such that UT passes
UT
> Cherry pick files from on change deletion commit 202205

- gnmi_server/server_test.go
- sonic_data_client/db_client.go
Key is missing in on change updates
Current:
root@efb973f6ce02:~# python /root/gnxi/gnmi_cli_py/py_gnmicli.py -g -t X -p 50051 -m subscribe -x NEIGH_STATE_TABLE -xt STATE_DB -o ndastreamingservertest --subscribe_mode 0 --submode 1 --interval 0 --update_count 2 --create_connections 1
```
2023-07-20 22:05:25.146156 response received:
sync_response: true
2023-07-20 22:05:31.271959 response received:
update {
timestamp: 1689890731162239986
prefix {
target: "STATE_DB"
}
update {
path {
elem {
name: "NEIGH_STATE_TABLE"
}
}
val {
json_ietf_val: "{\"peerType\":\"e-BGP\",\"state\":\"Active\"}"
}
}
}
```
Changed:
```
2023-07-20 22:01:56.251096 response received:
sync_response: true
2023-07-20 22:02:15.558270 response received:
update {
timestamp: 1689890542962488225
prefix {
target: "STATE_DB"
} …
```
> Backport Add key to on change updates (#138) to 202205

- gnmi_server/server_test.go
- sonic_data_client/db_client.go
- testdata/NEIGH_STATE_TABLE.txt
Key is missing in on change updates
Current:
root@efb973f6ce02:~# python /root/gnxi/gnmi_cli_py/py_gnmicli.py -g -t X -p 50051 -m subscribe -x NEIGH_STATE_TABLE -xt STATE_DB -o ndastreamingservertest --subscribe_mode 0 --submode 1 --interval 0 --update_count 2 --create_connections 1
```
2023-07-20 22:05:25.146156 response received:
sync_response: true
2023-07-20 22:05:31.271959 response received:
update {
timestamp: 1689890731162239986
prefix {
target: "STATE_DB"
}
update {
path {
elem {
name: "NEIGH_STATE_TABLE"
}
}
val {
json_ietf_val: "{\"peerType\":\"e-BGP\",\"state\":\"Active\"}"
}
}
}
```
Changed:
```
2023-07-20 22:01:56.251096 response received:
sync_response: true
2023-07-20 22:02:15.558270 response received:
update {
timestamp: 1689890542962488225
prefix {
target: "STATE_DB"
} …
```
> Add key to on change updates (#138) to 202012

- gnmi_server/server_test.go
- sonic_data_client/db_client.go
It is possible that in some edge cases, json.Marshal is unable to serialize map to JSON and panics. I am adding some additional logging at a higher log level and the ability for the function to recover from the panic with a deferred recover function.
Add deferred recover function when JSON serialization is done and drop the query when unable to provide a JSON to gnmi TypedValue. Add additional logging to give more context of state of map as well as data retrieved from Redis.
UT
> Recover from potential panic when doing map to JSON serialization (#161)

- sonic_data_client/virtual_db.go
- testdata/CONFIG_PFCWD_PORTS.txt
ADO: 26034082
Currently Pfcwd query is not working as the mapping of Pfwd to oid is broken due to incorrect table name. Fix table name and corresponding UT.
Fix table name and corresponding UT.
UT
> Fix COUNTERS/Ethernet*/Pfcwd query

- dialout/dialout_client/dialout_client.go
- dialout/dialout_client/dialout_client_test.go
- gnmi_server/connection_manager.go
- gnmi_server/server_test.go
- gnmi_server/transl_sub_test.go
- sonic_data_client/db_client.go
- sonic_data_client/events_client.go
- sonic_data_client/mixed_db_client.go
- sonic_data_client/virtual_db.go
- sonic_db_config/db_config.go
- sonic_db_config/db_config_test.go
sonic_db_config/db_config.go reads from database configuration json to get database configuration, but swsscommon has provided the same feature.
Use swsscommon API to read database configuration.
Pending on below PR to clear database configuration for unit test.
https://github.com/sonic-net/sonic-swss-common/pull/843
Run unit test.
> Use swsscommon API to read database configuration

- sonic_data_client/virtual_db.go
- testdata/CONFIG_PFCWD_PORTS.txt
In some cases in PFC_WD table there are keys such as "PFC_WD|GLOBAL" and GLOBAL cannot be mapped to COUNTERS_QUEUE_NAME_MAP so we run into an error since we cannot retrieve counters for key with not interface declared.  
Omit keys from PFC_WD that do not declare an interface
UT/manaul testing
> Account for GLOBAL key in PFC_WD

- sonic_data_client/db_client.go
What I did:
For supporting multi-asic as described here: https://github.com/sonic-net/sonic-telemetry/pull/77 we added support to handle `ASICx1` suffix in the target DB path. We  should only use that suffix  if the device is multi-asic else we can ignore it. This PR handle this case.
Why I did:
Telemetry Client can pass `ASICx` even for single asic device. To protect from that condition this change has been added.
How I verify:
Manually Verified . Before the fix client was getting error. After change it is getting data as expected.
> Use ASICx suffix in DB target path only if the device is multi-asic

- gnmi_server/server_test.go
- sonic_data_client/non_db_client.go
#25377424
Expected to pass SONiC.20XX, currently passing sonic.20XX
string change
UT
> Fix "sonic" string in OTHERS/osversion/build

- sonic_data_client/db_client.go
Cherry-pick of PR: https://github.com/sonic-net/sonic-gnmi/pull/184
> [202305] Use ASICx suffix in DB target path only if the device is multi-asic

- telemetry/telemetry.go
- telemetry/telemetry_test.go
Currently we are using a custom flagset, however glog requires that it's flags like logtostderr and v, be part of the global flag set. I parse cmd line args such that we call flag.Parse on only the glog global flags and then call the custom flagset parse on non glog flags.
Parse os.args such that we separate it into glog flags and telemetry flags. Call flag.Parse() to set up the global flags that glog requires, then flagset.Parse() to set up the flags that telemetry config will use.
UT
> Call flag.Parse() to parse global flags like -logtostderr

- gnmi_server/server_test.go
- sonic_data_client/mixed_db_client.go
- test/test_gnmi_appldb.py
- test/test_gnmi_configdb.py
- test/test_gnmi_countersdb.py
We need to update sonic-gnmi to support new GNMI path schema.
HLD PR: https://github.com/sonic-net/SONiC/pull/1625
I add a new element in GNMI path to support database instance.
```
/APPL_DB/localhost/DASH_VNET_TABLE/vnet1/
```
The second element is used for target database instance, and it's localhost by default.
Run unit test for sonic-gnmi.
Run end to end test for dash and gnmi.
> Update GNMI path schema

- gnmi_server/server_test.go
- pytest.ini
- sonic_data_client/client_test.go
- sonic_data_client/mixed_db_client.go
- sonic_db_config/db_config.go
- sonic_db_config/db_config_test.go
- test/test_gnmi_appldb.py
- test/test_gnmi_configdb.py
- test/test_gnmi_countersdb.py
- test/test_gnmi_dpu_appldb.py
- test_utils/test_utils.go
- testdata/database_config_dpu.json
- testdata/database_global_dpu.json
We have updated database configuration to support multiple databases for smartswitch.
And then we need to update sonic-gnmi to support new database configuration and new GNMI path for smartswitch.
HLD PR: https://github.com/sonic-net/SONiC/pull/1625
* Support new database configuration
```
{
"INCLUDES" : [
{
"include" : "../../redis/sonic-db/database_config.json"
},
{
"container_name" : "dpu0",
"include" : "../../redisdpu0/sonic-db/database_config.json"
}
],
"VERSION" : "1.0"
}
```
Use a single layer instance for each device to support multiple asic and multiple dpu.
For example, for multiple asic, the instances can be named localhost, asic0, asic1, and so on. For multiple dpu, the instances can be named localhost, dpu0, dpu1, and so on. For multiple asic npu and multiple dpu, the …
> Support multiple database for DPU

- sonic_data_client/virtual_db.go
- testdata/CONFIG_PFCWD_PORTS.txt
Reverts all changes related to Pfcwd query
Revert 178 and 173
Tested in 202305
Removed all PORT_QOS_MAP keys except for global.
Current version of 20230531.24 fails when querying COUNTERS/Ethernet with error: virtual_db.go:170] redis get field failed for CONFIG_DB in namsepace , key = PORT_QOS_MAP|global, field = pfc_enable, err: redis: nil
Installed deb with reverted changes
Query will succeed and print log
virtual_db.go:143] PFC WD not enabled on device
> Revert PR:178 Account for GLOBAL key in PFC_WD and Revert PR:173 Fix COUNTERS/Ethernet*/Pfcwd query

- sonic_data_client/mixed_db_client.go
https://github.com/sonic-net/sonic-buildimage/pull/16957
Above PR introduced "\n" in config_db, and current GNMI implementation does not support such config.
Update yang validation part to read config from file.
Run GNMI end to end test.
> Support control character in config

- dialout/dialout_client/dialout_client_test.go
- gnmi_server/server_test.go
- gnmi_server/transl_sub_test.go
- go.mod
- go.sum
Build pipeline is broken, and build error is introduced bye sonic-mgmt-common: https://github.com/sonic-net/sonic-mgmt-common/pull/125
Update go.mod and go.sum
Run azure pipeline to verify build
> Fix build error from sonic-mgmt-common

- sonic_data_client/client_test.go
- sonic_data_client/mixed_db_client.go
Fix mixed_db_client memory leak.
Found memory leak in mixed_db_client.
Add delete code for all sonic-swss-common lib resource.
Manually test.
Fix mixed_db_client memory leak.
> Fix mixed_db_client memory leak.

- sonic_data_client/client_test.go
- sonic_data_client/mixed_db_client.go
Fix ZMQ memory leak in unit test.
Found memory leak in mixed_db_client test case.
Delete global variable in unit test.
Manually test.
Fix ZMQ memory leak in unit test.
> Fix ZMQ memory leak in unit test.

- azure-pipelines.yml
For libswsscommon, instead of getting the artifacts from the sonic-buildimage repo, get it from the sonic-swss-common repo instead. The version in sonic-buildimage might be behind because the submodule update hasn't happened. That way, it's testing with the latest code, and also matches the go compilation where it uses the latest of sonic-swss-common.
> Use the latest libswsscommon artifacts from the repo

- sonic_data_client/client_test.go
- sonic_data_client/json_client.go
- sonic_data_client/mixed_db_client.go
- test/test_gnmi_configdb.py
- test/test_gnmi_configdb_patch.py
GCU has verified BGP configuration, we need to verify that GNMI can support the same BGP configuration.
Because GCU end2end test uses jsonpatch replace operation for BGP, we need to update GNMI replace operation for incremental config.
And we should not generate jsonpatch from string.
Microsoft ADO: 27231737
This unit test uses BGP configuration from GCU test.
This unit test generates GNMI request for BGP and use jsonpatch to verify patch file generated by GNMI server.
I also update gnmi replace implementation to support jsonpatch replace operation.
I generate jsonpatch from map.
> Improve GNMI incremental config and add unit test for BGP

- test/test_gnmi_configdb_patch.py
GCU has verified DHCP relay configuration, we need to verify that GNMI can support the same DHCP relay configuration.
Microsoft ADO: 27231787
This unit test uses DHCP relay configuration from GCU test.
This unit test generates GNMI request for DHCP relay and use jsonpatch to verify patch file generated by GNMI server.
> Add unit test for DHCP relay

- test/test_gnmi_configdb_patch.py
GCU has verified dynamic ACL configuration, we need to verify that GNMI can support the same dynamic ACL configuration.
Microsoft ADO: 28469784
This unit test uses dynamic ACL configuration from GCU test.
This unit test generates GNMI request for dynamic ACL and use jsonpatch to verify patch file generated by GNMI server.
Run gnmi unit test
> Add unit test for dynamic ACL

- test/test_gnmi_configdb_patch.py
GCU has verified ECN config, we need to verify that GNMI can support the same ECN config.
Microsoft ADO: 27231797
This unit test uses ECN config from GCU test.
This unit test generates GNMI request for DHCP relay and use jsonpatch to verify patch file generated by GNMI server.
> Add unit test for ECN config

- test/test_gnmi_configdb_patch.py
GCU has verified eth interface, we need to verify that GNMI can support the same eth interface.
Microsoft ADO: 27231799
This unit test uses eth interface from GCU test.
This unit test generates GNMI request for eth interface and use jsonpatch to verify patch file generated by GNMI server.
> Add unit test for eth interface

- test/test_gnmi_configdb_patch.py
GCU has verified IPV6 configuration, we need to verify that GNMI can support the same IPV6 configuration.
Microsoft ADO: 27231810
This unit test uses IPV6 configuration from GCU test.
This unit test generates GNMI request for IPV6 configuration and use jsonpatch to verify patch file generated by GNMI server.
> Add unit test for IPV6

- test/test_gnmi_configdb_patch.py
GCU has verified K8S configuration, we need to verify that GNMI can support the same K8S configuration.
Microsoft ADO: 27231816
This unit test uses K8S configuration from GCU test.
This unit test generates GNMI request for K8S configuration and use jsonpatch to verify patch file generated by GNMI server.
> Add unit test for k8s config

- test/test_gnmi_configdb_patch.py
GCU has verified mmu dynamic threshold configuration, we need to verify that GNMI can support the same mmu dynamic threshold configuration.
Microsoft ADO: 27231837
This unit test uses mmu dynamic threshold configuration from GCU test.
This unit test generates GNMI request for mmu dynamic threshold configuration and use jsonpatch to verify patch file generated by GNMI server.
> Add unit test for mmu dynamic threshold

- test/test_gnmi_configdb_patch.py
GCU has verified monitor config, we need to verify that GNMI can support the same monitor config.
Microsoft ADO: 27231840
This unit test uses monitor config from GCU test.
This unit test generates GNMI request for monitor config and use jsonpatch to verify patch file generated by GNMI server.
> Add unit test for monitor config

- test/test_gnmi_configdb_patch.py
GCU has verified ntp config, we need to verify that GNMI can support the same ntp config.
Microsoft ADO: 27231846
This unit test uses ntp config from GCU test.
This unit test generates GNMI request for ntp config and use jsonpatch to verify patch file generated by GNMI server.
> Add unit test for ntp

- test/test_gnmi_configdb_patch.py
GCU has verified pfcwd interval config, we need to verify that GNMI can support the same pfcwd interval config.
Microsoft ADO: 27231852
This unit test uses pfcwd interval config from GCU test.
This unit test generates GNMI request for pfcwd interval config and use jsonpatch to verify patch file generated by GNMI server.
> Add unit test for pfcwd interval

- test/test_gnmi_configdb_patch.py
GCU has verified pfcwd status config, we need to verify that GNMI can support the same pfcwd status config.
Microsoft ADO: 27231866
This unit test uses pfcwd status config from GCU test.
This unit test generates GNMI request for pfcwd status config and use jsonpatch to verify patch file generated by GNMI server.
> Add unit test for pfcwd status

- test/test_gnmi_configdb_patch.py
GCU has verified pg headroom config, we need to verify that GNMI can support the same pg headroom config.
Microsoft ADO: 27231872
This unit test uses pg headroom config from GCU test.
This unit test generates GNMI request for pg headroom config and use jsonpatch to verify patch file generated by GNMI server.
Run GNMI unit test
> Add unit test for pg headroom

- test/test_gnmi_configdb_patch.py
GCU has verified portchannel interface config, we need to verify that GNMI can support the same portchannel interface config.
Microsoft ADO: 27231875
This unit test uses portchannel interface config from GCU test.
This unit test generates GNMI request for portchannel interface config and use jsonpatch to verify patch file generated by GNMI server.
Run GNMI unit test
> Add unit test for portchannel interface

- test/test_gnmi_configdb_patch.py
GCU has verified syslog config, we need to verify that GNMI can support the same syslog config.
Microsoft ADO: 27231882
This unit test uses syslog config from GCU test.
This unit test generates GNMI request for syslog config and use jsonpatch to verify patch file generated by GNMI server.
Run GNMI unit test
> Add unit test for syslog config

- test/test_gnmi_configdb_patch.py
GCU has verified vlan interface config, we need to verify that GNMI can support the same vlan interface config.
Microsoft ADO: 27231884
This unit test uses vlan interface config from GCU test.
This unit test generates GNMI request for vlan interface config and use jsonpatch to verify patch file generated by GNMI server.
Run GNMI unit test
> Add unit test for vlan interface

- sonic_service_client/dbus_client.go
Currently we are using 60 seconds as timeout for GNMI dbus API, if GCU takes several minutes, GNMI will fail.
Microsoft ADO: 27231413
Now we use 180 seconds as timeout, and this is the same as NDM timeout for GCU.
Run GNMI unit test and end to end test.
> Improve timeout for GNMI dbus service

- sonic_data_client/mixed_db_client.go
- test/test_gnmi_countersdb.py
gnmi native subscribe API needs to support COUNTERS_DB.
Microsoft ADO: 25282671
Improve GNMI to support COUNTERS_DB.
Add unit test to verify subscribe poll mode with COUNTERS_DB.
> Improve GNMI native to support COUNTERS_DB

- sonic_data_client/client_test.go
- sonic_data_client/mixed_db_client.go
Return GNMI API error when ZMQ operation failed. 
When ZMQ is full, GNMI service crash.
Return API error instead of panic. 
Manually test.
Microsoft ADO (number only): 28694022
Return GNMI API error when ZMQ operation failed.
> Return GNMI API error when ZMQ operation failed.

- sonic_data_client/virtual_db.go
- testdata/CONFIG_PFCWD_PORTS.txt
This reverts commit 50849ce7b279b916dcb6782b88c9cb2d189c67d0.
> Revert "Replace PFC_WD_TABLE with PFC_WD (#173)"

- sonic_data_client/client_test.go
The yang model for bridge-midplane is not aligned with the actual implementation present in https://github.com/sonic-net/sonic-buildimage/pull/18178, 
This PR is to align the yang model to change `bridge_midplane` to `bridge-midplane` since this is the value used in the `systemd-networkd` in CONFIG_DB so that the yang validation does not fail
Changed `bridge_midplane` to `bridge-midplane` at all locations
> [Smartswitch] Yang model change for bridge midplane

- sonic_data_client/client_test.go
- sonic_data_client/mixed_db_client.go
Fix issue with getting DPU IP address from DHCP_SERVER_IPV4_PORT table
```
result     = ['Performing SetRequest Update, encoding=JSON_IETF  to  10.210.25.4  with the following gNMI Path\n ------------------... Get ZMQ address failed: Get DPU address failed: Can't read bridge-midplane|dpu0:ips from DHCP_SERVER_IPV4_PORT table"]
```
The DPU IP addresses in `DHCP_SERVER_IPV4_PORT` table are stored in the list container:
```
"DHCP_SERVER_IPV4_PORT": {
"bridge-midplane|dpu0": {
"ips": [
"169.254.200.1"
]
},
"bridge-midplane|dpu1": {
"ips": [
"169.254.200.2"
]
},
"bridge-midplane|dpu2": {
"ips": [
"169.254.200.3"
]
},
"bridge-midplane|dpu3": {
"ips": [
"169.254.200.4"
]
}
},
```
Use the correct key to access the container:
```
sonic-db-cli CONFIG_DB hgetall …
```
> Fix issue with getting DPU IP address from DHCP_SERVER_IPV4_PORT table

- gnmi_server/client_subscribe.go
- gnmi_server/server.go
- sonic_data_client/client_test.go
- sonic_data_client/mixed_db_client.go
- telemetry/telemetry.go
Add mgmt VRF support.
Fix this issue:
https://github.com/sonic-net/sonic-buildimage/issues/19638
Add VRF parameter and bind ZMQ to VRF.
Manually test.
Add new UT.
Microsoft ADO (number only): 29064735
Add mgmt VRF support.
> Add mgmt VRF support.

- Makefile
axw gocov was modified to use go 1.22 while currently sonic-gnmi still uses 1.13 a few days ago from this PR creation date. To ensure pipeline still works, we are specifying last stable version of axw gocov that still worked with sonic-gnmi pipeline which was 1.1.0
Specify gocov version
Pipeline
> Use version of gocov supported by sonic-gnmi

- Makefile
axw gocov was modified to use go 1.22 while currently sonic-gnmi still uses 1.13 a few days ago from this PR creation date. To ensure pipeline still works, we are specifying last stable version of axw gocov that still worked with sonic-gnmi pipeline which was 1.1.0
Specify gocov version
Run pipeline
> Fix pipeline for 202305 branch

- common_utils/context.go
- gnmi_server/gnoi.go
- sonic_service_client/dbus_client.go
- test/test_gnoi.py
Add support for HALT reboot method for Reboot gNOI API
Implement changes for HaltSystem() function to be called when HALT reboot method is invoked.
Unit tests
> Add support for RebootMethod_HALT for Reboot API

- gnmi_server/clientCertAuth.go
- gnmi_server/debug.go
- gnmi_server/gnoi.go
- gnmi_server/server.go
- gnmi_server/server_test.go
- telemetry/telemetry.go
- telemetry/telemetry_test.go
Add cert authorization with common name support.
Support cert authorization with common name.
Load trusted cert common name from config DB and check cert common name. 
Manually test.
Add new UT.
Microsoft ADO (number only): 25226269
Add cert authorization with common name support.
> [202405] Add cert authorization with common name support. 

- gnmi_server/clientCertAuth.go
- gnmi_server/debug.go
- gnmi_server/gnoi.go
- gnmi_server/server.go
- gnmi_server/server_test.go
- telemetry/telemetry.go
Add cert authorization with common name support.
Support cert authorization with common name.
Load trusted cert common name from config DB and check cert common name. 
Manually test.
Add new UT.
Microsoft ADO (number only): 25226269
Add cert authorization with common name support.
> [202311] Add cert authorization with common name support. 

- sonic_service_client/dbus_client.go
We found that GCU takes about 10 minutes to update ACL rules
Update dbus timeout to 10 minutes so that we can use GNMI to update ACL rules.
Run GNMI unit test and end to end test
> Update dbus timeout to 10 minutes

- sonic_service_client/dbus_client.go
We found that GCU takes about 10 minutes to update ACL rules
Backport https://github.com/sonic-net/sonic-gnmi/pull/326
Update dbus timeout to 10 minutes so that we can use GNMI to update ACL rules.
Run GNMI unit test and end to end test
> [202311] Update dbus timeout to 10 minutes

- sonic_service_client/dbus_client.go
We found that GCU takes about 10 minutes to update ACL rules
Backport https://github.com/sonic-net/sonic-gnmi/pull/326
Update dbus timeout to 10 minutes so that we can use GNMI to update ACL rules.
Run GNMI unit test and end to end test
> [202405] Update dbus timeout to 10 minutes

- gnmi_server/client_subscribe.go
It is found that if I run gnmi subscribe to db change with an invalid xpath, gnmi server has a panic because of nil pointer dereference. 
Test is against multi-asic chassis. In telemtery test test_on_change_updates is did not handle the multi-asic properly which sends out gnmi subscribe like this: python /root/gnxi/gnmi_cli_py/py_gnmicli.py -g -t 10.250.6.233 -p 50052 -m subscribe -x NEIGH_STATE_TABLE -xt STATE_DB -o ndastreamingservertest --subscribe_mode 0 --submode 1 --interval 0 --update_count 2 --create_connections 1
gnmi container restarts with a panic. 
Correct CLI commands should be: python /root/gnxi/gnmi_cli_py/py_gnmicli.py -g -t 10.250.6.233 -p 50052 -m subscribe -x NEIGH_STATE_TABLE/asic0 -xt STATE_DB -o ndastreamingservertest --subscribe_mode 0 --submode 1 --interval 0 …
> Fix a panic by gnmi subscribe to DB change with invalid xpath

- telemetry/telemetry.go
Add swss-common log level support to GNMI service
Improve GNMI debug experience
Initialize swss-common log level thread when GNMI start.
Manually test:
admin@vlab-01:~$ swssloglevel -l NOTICE -c telemetry
admin@vlab-01:~$ sudo tail -f /var/log/syslog
2024 Nov 22 05:30:03.876827 vlab-01 DEBUG gnmi#telemetry: :> select: enter
2024 Nov 22 05:30:04.734015 vlab-01 INFO systemd[1]: Starting sysstat-collect.service - system activity accounting tool...
2024 Nov 22 05:30:04.740683 vlab-01 INFO systemd[1]: Starting logrotate.service - Rotate log files...
2024 Nov 22 05:30:04.750069 vlab-01 DEBUG gnmi#telemetry: :< select: exit
2024 Nov 22 05:30:04.754189 vlab-01 DEBUG gnmi#telemetry: :- swssPrioNotify: Changing logger minPrio to NOTICE
Add new UT.
Microsoft ADO (number only): 30298614
Add …
> Add swss-common log level support to GNMI service

- gnmi_server/debug.go
- gnmi_server/gnoi.go
- gnmi_server/server.go
- gnmi_server/server_test.go
Microsoft ADO: 30073317
GNMI/GNOI services need to support role in API operation. RO user is not allowed to call write API.
We have supported common name to role mapping, and I have updated API authentication to verify role.
Run unit test and end to end test.
> Improve GNMI service to limit API access by role

- gnoi_client/config/flag.go
- gnoi_client/file/file.go
- gnoi_client/gnoi_client.go
- gnoi_client/sonic/jwt.go
- gnoi_client/sonic/sonic.go
- gnoi_client/system/kill_process.go
- gnoi_client/system/reboot.go
- gnoi_client/system/time.go
- gnoi_client/utils/creds.go
The gnoi/gnmi code in sonic-gnmi have some diamond dependency problems since different code can dependent on different version of gnoi/gnmi, leading to inability to implement newer services such as `containerz`, which comes after gnoi v0.4.0. Golang with its `go mod vendor` offers a way to solve this problem. But the code needs to be properly modularized to take advantage of this.
Untangle gnoi_client.go into separate modules such as `config`, `util`, `system`, `file` and `sonic`.
built and unit tested, also verified by copying the new gnoi_client binary to a VS and run sonic-mgmt gnoi_kill_process test.
> Better modularization for gnoi_client.go

- gnoi_client/gnoi_client.go
Better organization and format for gnoi_client.go
* `gofmt -w gnoi_client.go`
* Some client rpc entry point have service name preceding it (like `systemReboot`) and some doesn't (like `killProcess`). All entry point for rpc should have the service name preceding it.
This is a refactor. `make all` passes
> Better format for gnoi_client.go

- gnmi_server/server.go
Microsoft ADO: 30073317
GNMI crashed if there's no cname in GNMI_CLIENT_CERT table
Check previous result before taking action
Run gnmi unit test and end to end test
> Fix roles checking if cname not exist

- common_utils/context.go
- gnmi_server/gnoi.go
- gnmi_server/server.go
- gnmi_server/server_test.go
- gnoi_client/gnoi_client.go
- gnoi_client/os/verify.go
- sonic_service_client/dbus_client.go
- sonic_service_client/dbus_client_test.go
- test/test_gnoi.py
- test/utils.py
Supports OS.Verify for Upgrading OS
Implement GNOI server and client for GNOI.OS.Verify
Backend PR: https://github.com/sonic-net/sonic-host-services/pull/206
On Mellanox:
gnoi_client -target 127.0.0.1:50052 -logtostderr -insecure -module OS -rpc Verify
OS Verify
{"version":"SONiC-OS-20240510.23"}
GNOI OS.Verify implementation.
Backend PR: https://github.com/sonic-net/sonic-host-services/pull/206
> GNOI Implementation of OS.Verify

- gnmi_server/gnoi.go
- sonic_service_client/dbus_client.go
- sonic_service_client/dbus_client_test.go
DBusClient lacks a close method. We need to rely on GC to close the connection.
Add a Close method to DBusClient and use it in GNMI server
unit test and on DUT.
> Add a Close method to DBusClient and use it in GNMI server

- Makefile
- gnmi_server/server_test.go
- gnmi_server/transl_sub_test.go
- go.mod
- go.sum
- patches/gnmi_cli.all.patch
- patches/gnmi_get.patch
- patches/gnmi_path.patch
- patches/gnmi_set.patch
- patches/gnmi_xpath.patch
- sonic_data_client/client_test.go
Microsoft ADO: 27225139
We should not use Jipanyang's personal repo in sonic-gnmi
Use google/gnxi to replace jipanyang/gnxi and update related patches
Run gnmi unit test and end to end test
> Remove the dependency on Jipanyang's personal repository

- gnmi_server/server_test.go
- pytest.ini
- sonic_data_client/mixed_db_client.go
- test/test_gnmi_configdb_patch.py
Fix https://github.com/sonic-net/sonic-buildimage/issues/20875
GNMI set does not support multi-asic environment
Add namespace in GCU patch for multi-asic
Run gnmi unit test and end to end test
> Update incremental config to support multi-asic

- transl_utils/transl_utils.go
Modified transl's Bulk processing API to support new translib Bulk API
The Translib API for bulk operations in sonic-mgmt-common has been updated for gNMI conformance. This pull request modifies the sonic-gnmi Bulk API to ensure compliance with these changes.
Modified transl_utils' processBulkAPI
Verified by making gNMI bulk request
> TransL Bulk API enhancement

- proto/sonic_internal.pb.go
- proto/sonic_internal.proto
- sonic_data_client/db_client.go
- sonic_data_client/mixed_db_client.go
Backport PR of #371 
Tested on latest 202411 branch with and without this revert
Without this revert, telemetry crashed within 5-10 minutes, and have not seen it crash with this revert for 20+ mins
Tested this revert on latest 202411 for the SKUs
Arista 7260, Cisco 8102, Mellanox SN 2700, Arista 7060 (slim)
> Manually revert delete field logic 202411

- gnmi_server/clientCertAuth.go
- gnmi_server/server_test.go
Add cert multiple roles support
Some scenarios need GNMI support multiple roles
Change CONFIG_DB schema and read multiple roles from CONFIG_DB
Manually test.
Add new UT.
Microsoft ADO (number only): 31561802
Add cert multiple roles support
> Add cert multiple roles support

- common_utils/context.go
- sonic_data_client/mixed_db_client.go
- sonic_service_client/dbus_client.go
- sonic_service_client/dbus_client_test.go
- test/test_gnmi_configdb.py
By default, gNMI does a version of `config reload` when passed a full config. This is disruptive, since it requires services to be restarted for it to take effect. It's also not intuitive; all of the other SET gnmi commands take place immediately. By enhancing the full config endpoint handling to trigger `config replace` instead of the gnmi-specific version of reload that exists today, we resolve both of those issues.
The existing implementation uses a full config DELETE given alongside a full config UPDATE to represent a reload. We can leave that syntax and behavior intact and instead add logic to handle a full config REPLACE.
fixes [Issue 357](https://github.com/sonic-net/sonic-gnmi/issues/357)
There is already a D-BUS endpoint implemented for `config replace`, so all this takes is a …
> Issue #357: Use ConfigReplace when full config is sent over gNMI

- gnmi_server/client_subscribe.go
- gnmi_server/debug.go
- gnmi_server/gnoi.go
- gnmi_server/gnoi_system.go
- gnmi_server/server.go
- gnmi_server/server_test.go
- sonic_data_client/mixed_db_client.go
Support new role for GNMI: gnmi_noaccess, gnmi_readonly, gnmi_readwrite, gnmi_config_db_noaccess, gnmi_config_db_readonly, gnmi_config_db_readwrite, ...
Microsoft ADO: 30073317
Update authentication logic:
1. if role is noaccess, reject read and write operation
2. if role is readonly, reject write operation, accept write operation
3. if role is readwrite, accept read and write operation
4. if role is empty, reject write operation, accept write operation
telemetry, gnmi and gnoi support this new authentication logic.
Run unit test and end to end test
> Update authenticate to support gnmi role and gnoi role

- azure-pipelines.yml
Update agent-pool to 22.04 since 20.04 is no longer available.
Ubuntu 20.04 agent is no longer available.
Update agent-pool to use ubuntu 22.04
See azure-pipeline runs.
> Update agent-pool to use ubuntu 22.04

- Makefile
- patches/0004-CloseWrite-event-support.patch
- telemetry/telemetry.go
- telemetry/telemetry_test.go
MS ADO: 33377547
If we have a slow writer to a cert file that is monitored such that they truncate the file, and write bytes at a time, we will see excessive amount of WRITE events such that our server will try to reload on each one. With CloseWrite supported, once a writer has finished writing to the file and closed the file we will then try the reload. We also add logic to distinguish between CREATE and IN_MOVED_TO events such that we will reload on IN_MOVED_TO but not CREATE events.
1) Added a patch for fsnotify to support CLOSE_WRITE events and distinguish between CREATE and IN_MOVED_TO events
2) Change telemetry server to monitor for CLOSE_WRITE instead of just WRITE events and monitor IN_MOVED_TO instead of CREATE events.
Patched is based off …
> Support CloseWrite event such that we don't reload on every Write event

- gnmi_server/gnoi.go
- gnmi_server/gnoi_file.go
- gnmi_server/gnoi_file_test.go
- gnoi_client/config/flag.go
- gnoi_client/file/file.go
- gnoi_client/gnoi_client.go
- go.mod
- sonic_service_client/dbus_fake_client.go
- sonic_service_client/dbus_fake_client_test.go
**[UMF] gNOI File Service - Test Results**
**Manual CLI Testing**
**Remove RPC**
```
admin@sonic:~$ touch /tmp/test_remove
admin@sonic:~$ ls /tmp/test_remove
/tmp/test_remove
admin@sonic:~$ docker exec -it gnmi gnoi_client -notls -insecure -module File -rpc Remove -jsonin '{"remote_file":"/tmp/test_remove"}'
File Remove
{}
admin@sonic:~$ ls /tmp/test_remove
ls: cannot access '/tmp/test_remove': No such file or directory
admin@sonic:~$ docker exec -it gnmi gnoi_client -notls -insecure -module File -rpc Remove -jsonin '{"remote_file":"/tmp/test_remove"}'
File Remove
Remove RPC failed: rpc error: code = Unknown desc = File not found: /tmp/test_remove
admin@sonic:~$ 
```
**Stat RPC**
```
admin@sonic:~$ docker exec -it gnmi gnoi_client -notls -insecure -module File -rpc Stat -jsonin …
```
> Add support for gNOI File Services

- common_utils/context.go
- gnmi_server/gnoi_reset.go
- gnmi_server/gnoi_reset_test.go
- gnmi_server/server.go
- gnoi_client/factory_reset/factory_reset.go
- gnoi_client/gnoi_client.go
- sonic_service_client/dbus_client.go
- sonic_service_client/dbus_client_test.go
- sonic_service_client/dbus_fake_client.go
- sonic_service_client/dbus_fake_client_test.go
``` 
"admin@sonic:~$ docker exec gnmi gnoi_client -target 127.0.0.1:8080 -notls -module FactoryReset -rpc Start -jsonin '{""factoryOs"": true}'
Start Factory Reset.
{"Response":{"ResetError":{"detail":"Method FactoryReset.Start is unimplemented."}}}
```
```
"admin@sonic:~$ docker exec gnmi gnoi_client -target 127.0.0.1:8080 -notls -module FactoryReset -rpc Start -jsonin '{""factoryOs"": false}'
Start Factory Reset.
{"Response":{"ResetError":{"detail":"Method FactoryReset.Start is unimplemented."}}}
```
```
"admin@sonic:~$ docker exec gnmi gnoi_client -target 127.0.0.1:8080 -notls -module FactoryReset -rpc Start -jsonin '{""factory_os"": true, ""zero_fill"": true}'
Start Factory Reset.
{""Response"":{""ResetError"":{"detail":"zero_fill operation is currently unsupported."}}}"
```
``` …
```
> [gNOI] Add support for gNOI Factory Reset

- azure-pipelines.yml
- gnmi_server/clientCertAuth.go
- gnmi_server/server_test.go
Add cert multiple roles support
This is cherry-pick PR for https://github.com/sonic-net/sonic-gnmi/pull/366
Some scenarios need GNMI support multiple roles
Change CONFIG_DB schema and read multiple roles from CONFIG_DB
Manually test.
Add new UT.
Microsoft ADO (number only): 31561802
Add cert multiple roles support
> [202311] Add cert multiple roles support

- gnmi_server/interface_transceiver_cli_test.go
- show_client/interface_transceiver_cli.go
- show_client/show_paths.go
- testdata/TRANSCEIVER_STATUS_SW.txt
Add support for SHOW interface tansceiver error-status
This PR will add the implementation of a new data path "SHOW" that will allow clients to query PATHS similar to show commands that are executed on the host.
In this PR we are focusing on the implementation of show interface tansceiver error-status in telemetry such that the following paths are supported. SHOW/interface/transceiver/error-status
Added a new SHOW client that supports GET operations only and can support DB reads.
UT and manually run
```
root@str5-7060x6-512-5:/# gnmi_get -xpath_target SHOW -xpath interface/transceiver/error-status -target_addr 127.0.0.1:50051 -logtostderr -insecure true
== getRequest:
prefix: <
target: "SHOW"
>
path: <
elem: <
name: "interface"
>
elem: <
name: "transceiver"
>
elem: <
name: "error-status" …
```
> Add SHOW implementation for interface transceiver error-status.

- gnmi_server/chassis_module_cli_test.go
- show_client/chassis_module_cli.go
- show_client/show_common.go
- show_client/show_opts.go
- show_client/show_paths.go
- testdata/CHASSIS_MODULE_CONFIG.txt
- testdata/CHASSIS_MODULE_STATE.txt
Add support for `show chassis module status`
Implement logic is smae as sonic-utilites.
UT and manual verifeid in DUT:
```
admin@str3-8102-07:~$ docker exec -it telemetry gnmi_get -xpath_target SHOW -xpath chassis/module/status[dpu=DPU1] -target_addr 127.0.0.1:50051 -logtostderr -insecure true
== getRequest:
prefix: <
target: "SHOW"
>
path: <
elem: <
name: "chassis"
>
elem: <
name: "module"
>
elem: <
name: "status"
key: <
key: "dpu"
value: "DPU1"
>
>
>
encoding: JSON_IETF
== getResponse:
notification: <
timestamp: 1755248754884228628
prefix: <
target: "SHOW"
>
update: <
path: <
elem: <
name: "chassis"
>
elem: <
name: "module"
>
elem: <
name: "status"
key: <
key: "dpu"
value: "DPU1"
>
>
>
val: <
json_ietf_val: "{\n  \"DPU1\": {\n    \"name\": \"DPU1\",\n    \"description\": \"AMD Pensando …
```
> Implement `show chassis module status`
