- azure-pipelines.yml
Transfer organization from Azure to sonic-net
> Fix pipeline.

- gnmi_server/server.go
- gnmi_server/server_test.go
- go.mod
We need to enhance authentication and authorization for sonic-gnmi, and the first step is to add log.
Add log for auth user and roles.
Run unit test.
> Add log for authentication and add unit test.

- Makefile
- gnmi_server/server_test.go
Unit test failure does not block PR.
Enable unit test, and fix failed test case.
Run unit test for sonic-gnmi.
Fix #17
> Enable unit test

- Makefile
- azure-pipelines.yml
We should not run unit test without redis server.
Check redis.sock, if there's no redis.sock, do not run unit test.
Run unit test for gnmi, and build image.
> Improve unit test for gnmi

- gnmi_server/server_test.go
- go.mod
sonic-buildimage has a pipeline for armhf, and gomonkey v1 does not support arm.
Use gomonkey v2 instead.
Run sonic-buildimage pipeline for armhf.
> Use gomonkey v2 to support arm64.

- sonic_data_client/transl_data_client.go
GNMI unit test failed at transl_data_client.go.
Update transl_data_client.go.
Build sonic-gnmi and run unit test.
> Fix format for transl client

- azure-pipelines.yml
Add 202012 branch to PR checker
Modify azure-pipelines.yml
> Add 202012 branch to pr checker

- azure-pipelines.yml
src directory is no longer sonic-telemetry, it is sonic-gnmi
change dir name
> Change dir name in pipeline

- Makefile
- gnmi_server/server_test.go
Enable unit test for 202012 branch
Backport master PR
> [202012] Enable unit test

- README.md
- azure-pipelines.yml
redis-server was unable to be located, breaking all sonic-gnmi builds. Add apt-get update to fix issue
modify azp yml file
pipeline
> Add get-update to azp yml

- azure-pipelines.yml
Add diff coverage for 202012 branch
code coverage needed
pipeline
> [202012] Add diff coverage

- Makefile
Cherry pick: https://github.com/sonic-net/sonic-gnmi/pull/40
cherry-pick https://github.com/sonic-net/sonic-gnmi/pull/40
> [202012] Workaround gomonkey for armhf

- azure-pipelines.yml
sonic-net.sonic-gnmi pipeline is broken due to swss-common change.
Fix correct artifact.
Pipeline should be pass if this PR works.
Fix sonic-swss-common issue which breaks gnmi pipeline.
> Fix sonic-swss-common issue which breaks gnmi pipeline.

- gnmi_server/server.go
Keep parity with subscribe logging request (refer to https://github.com/sonic-net/sonic-gnmi/blob/master/gnmi_server/client_subscribe.go#L119)
Changed log level
> Change log level of gnmi GET paths

- gnmi_server/server.go
Cherry pick commit: 4a8964a0d25b893af71a93cd711ff23e09ed12ae
> [202012] Change log level of gnmi GET paths

- azure-pipelines.yml
Want to support PR/code coverage pipelines for all branches. Update yml to use wildcard to generalize instead of specifying each one.
Updated yml
Pipeline
> Update azp yml to generalize branch names 

- Makefile
- azure-pipelines.yml
- gnmi_server/client_subscribe.go
- gnmi_server/connection_manager.go
- gnmi_server/server.go
- gnmi_server/server_test.go
- go.mod
- telemetry/telemetry.go
Backport PRs to keep master and 202211 in parity.
Following commits are included:
`@FengPan-Frank [Fix sonic-swss-common issue which breaks gnmi pipeline. 5adc269`
`@zbud-msft Limit client connections connecting to gnmi server da4d764`
`@FengPan-Frank Bump golang version for fixing unsafe injection issue CVE-2021-33195 e497f61`
`@zbud-msft Change log level of gnmi GET paths 4a8964a`
`@FengPan-Frank Enable "-race" on telemetry test patch - 1 1b1d4ec`
`@zbud-msft Add keep alive policies to close idle client connections 258b887`
`@zbud-msft Fix bug in consecutive client connections f576fe0`
`@zbud-msft Update azp yml to generalize branch names 59b332f`
Backport PRs
Pipeline
> Backport PRs to 202211

- azure-pipelines.yml
Why I did it
Want to support PR/code coverage pipelines for all branches. Update yml to use wildcard to generalize instead of specifying each one.
How I did it
Updated yml
How to verify it
Pipeline
> [202012] Backport Update azp yml to generalize branch names (#106)

- sonic_data_client/db_client.go
ADO tracking #: 23021533
In production, there change be many excessive logs from on change updates that can eat up disk space
Change log level so that we can enable those logs dynamically if needed.
> Change log levels of on change updates

- Makefile
- azure-pipelines.yml
- gnmi_server/server_test.go
- sonic_data_client/transl_data_client.go
ADO # (For tracking purposes): 23062915
Merging necessary commits for 202205 pipeline with UT/Code coverage to run. These are the commits that should enable PR checker and UT in subsequent PRs to 202205. Will need force merge as the PR checker will not run for this PR.
9e2ad0a07d8861dba6b9d95069bb79d2c065c202 - workaround for gomonkey
7c310883b05403f93813ea32b5906e10ab6ceb91 - fix makefile error
af1ec1926ece41127fcfd5dccca6193ec29b654d - change diff cov to 80
67b7fb2a2b12013db0b4114576eb686167aea4ab - fix get-update
5d6c47fad29e24cff63240f66089c3668eb04fa9 - add net core and code cov results
89d46ff15359587b9b1d6319639b8623c9993262 - enable unit test
e8e4335bf7831aa081119c7de76bf8440794a7af - change dir name in pipeline
6dc4bb96e970df89d583fe9522ff95efa8eb6d75 - update azp …
> [202205] Merge necessary commits for enabling code coverage and UT in PR checker

- Makefile
Enable golang race detector in new added test transl_utils.
Always run outer loop tests with "-race" enabled
Use unit test.
> Enable "-race" on new added test transl_utils

- gnmi_server/server.go
ADO # 16208453
Backport https://github.com/sonic-net/sonic-gnmi/commit/7bb6f80301446416c6117f0af03a3e12dfa17757
git cherry-pick
pipeline
> [202205] Backport "update gnmi_get log"

- Makefile
…ention.
Rename --enable-dialout option into ENABLE_DIALOUT to follow the convention, so that internal config change has no convention break.
Rename the option.
local make.
> Rename --enable-dialout option into ENABLE_DIALOUT to follow the convention

- gnmi_server/server.go
- patches/gnmi_get.patch
- patches/gnmi_set.patch
- sonic_data_client/db_client.go
- sonic_data_client/mixed_db_client.go
- test/test_gnmi_appldb.py
- test/utils.py
Need to support GNMI request with proto encoding.
Update gnmi client and gnmi server to support both json ietf and proto encoding.
> Support proto encoding

- sonic_data_client/client_test.go
- sonic_data_client/json_client.go
Need to read whole config db with GNMI get.
Update json client to return checkpoint file.
Run unit test.
> Support get all with json client

- sonic_data_client/mixed_db_client.go
Full path has dependency for prefix.
Always generate full path with API.
Run sonic-gnmi unit test.
> Improve full path logic

- azure-pipelines.yml
> Install necessary deb instead of entire image

- gnmi_server/server_test.go
- testdata/NEIGH_STATE_TABLE.txt
ADO: 24996556
On change mode backport PR requires changes to prepareStateDb(), mainly loading data set NEIGH_STATE_TABLE, as our UT is based off that data set.
Backport certain needed changes from another PR such that UT passes
UT
> Cherry pick prepare state db 202305

- Makefile
Manual cherrypick dialout build flag PR to 202205.
Manual cherrypick dialout build flag PR to 202205.
Verified by image.
> Manual cherrypick dialout build flag PR to 202205.

- Makefile
Cherrypick dialout build flag PR to 202012
Cherrypick
verified by image.
> Manual cherrypick dialout build flag PR to 202012.

- gnmi_server/server_test.go
- sonic_data_client/non_db_client.go
Reverts sonic-net/sonic-gnmi#191
> Revert "[action] [PR:190] Fix sonic string in osversion/build (#190)"

- sonic_data_client/mixed_db_client.go
- sonic_db_config/db_config_test.go
- testdata/database_config_dpu.json
GNMI is using wrong NewDBConnector API.
Specify dbkey in NewDBConnector API.
Run unit test and end to end test.
> Update DB connector to use dbkey

- gnmi_server/server_test.go
- sonic_data_client/non_db_client.go
Reverts sonic-net/sonic-gnmi#202
> Revert "Revert "[action] [PR:190] Fix sonic string in osversion/build (#190)""

- sonic_data_client/virtual_db.go
- testdata/CONFIG_PFCWD_PORTS.txt
Reverts sonic-net/sonic-gnmi#211
> Revert "[action] [PR:173] Replace PFC_WD_TABLE with PFC_WD (#173)"

- sonic_data_client/mixed_db_client.go
- sonic_db_config/db_config.go
Fix https://github.com/sonic-net/sonic-buildimage/issues/18712
While running the sonic-mgmt dash tests, the memory usage for the gnmi container (telemetry process) constantly grows until gets restarted by monit_gnmi
Remove memory allocated by swsscommon API, and improve memory usage.
Run gnmi unit test and run gnmi end to end test.
> Fix memory leak

- gnmi_server/server_test.go
Some translib unit test failed in pipeline.
Disable related unit test, and we will enable them when sonic-mgmt-common is ready.
Run build pipeline.
> Disable translib unit test

- gnmi_server/server_test.go
- sonic_data_client/client_test.go
- sonic_data_client/mixed_db_client.go
- sonic_db_config/db_config.go
- sonic_db_config/db_config_test.go
I find some memory in unit test.
Fix memory leak in unit test, and improve memory leak for some corner case.
Run sonic-gnmi unit test.
> Fix memory leak in unit test

- sonic_data_client/mixed_db_client.go
Microsoft ADO: 28064504
GNMI full config end to end test is broken.
Fix yang validation part to send file name to python code.
Run gnmi unit test and end to end test.
> Fix GNMI full config update

- sonic_data_client/virtual_db.go
- testdata/CONFIG_PFCWD_PORTS.txt
Reverts sonic-net/sonic-gnmi#178
> Revert "Account for GLOBAL key in PFC_WD"

- sonic_data_client/mixed_db_client.go
gnmi yang validation failed
Use file name instead of file content.
Run unit test and end to end test
> Fix yang validation

- Makefile
- test/test_gnmi_configdb_patch.py
GCU has verified CACL configuration, we need to verify that GNMI can support the same CACL configuration.
Microsoft ADO: 27231782
This unit test uses CACL configuration from GCU test.
This unit test generates GNMI request for CACL and use jsonpatch to verify patch file generated by GNMI server.
> Add unit test for CACL

- dialout/dialout_client/dialout_client_test.go
- gnmi_server/server_test.go
- gnmi_server/transl_sub_test.go
Build pipeline is broken, and build error is introduced bye sonic-mgmt-common: https://github.com/sonic-net/sonic-mgmt-common/pull/125
Disable related test
Run azure pipeline to verify build
> [202311] Fix build error from sonic-mgmt-common

- sonic_data_client/mixed_db_client.go
GNMI full config end to end test is broken.
Microsoft ADO: 28064504
Fix yang validation part to send file name to python code.
Run gnmi unit test and end to end test.
> [202311] Fix GNMI full config update

- test/test_gnmi_configdb_patch.py
GCU has verified incremental qos configuration, we need to verify that GNMI can support the same incremental qos configuration.
Microsoft ADO: 27231804
This unit test uses incremental qos configuration from GCU test.
This unit test generates GNMI request for incremental qos configuration and use jsonpatch to verify patch file generated by GNMI server.
> Add unit test for incremental QoS

- sonic_data_client/json_client.go
- test/test_gnmi_configdb_patch.py
GCU has verified lo interface configuration, we need to verify that GNMI can support the same lo interface configuration.
Microsoft ADO: 27231835
This unit test uses lo interface configuration from GCU test.
This unit test generates GNMI request for lo interface configuration and use jsonpatch to verify patch file generated by GNMI server.
> Add unit test for lo interface

- gnmi_server/server.go
https://github.com/sonic-net/SONiC/pull/1297
Requested change by ganglyu to Save on Set design.
moved the call to inside a branch
make save on set only when err is nil
> make save on set only when err is nil

- gnmi_server/client_subscribe.go
- patches/gnmi_cli.all.patch
- sonic_data_client/mixed_db_client.go
- test/test_gnmi_configdb.py
- test/utils.py
gnmi native does not support subscribe RPC.
Microsoft ADO: 25282671
Add API to support subscribe poll mode.
Add unit test to verify subscribe poll mode.
> Update gnmi-native to support subscribe poll mode

- sonic_data_client/client_test.go
- sonic_data_client/mixed_db_client.go
- test/test_gnmi_configdb.py
- test/test_gnmi_countersdb.py
- test/utils.py
gnmi native does not support subscribe RPC.
Microsoft ADO: 25282671
Add API to support subscribe stream mode.
Add unit test to verify subscribe stream mode.
Run gnmi unit test
> Update gnmi-native to support subscribe stream mode

- sonic_service_client/dbus_client.go
GNMI test failed on some sonic devices, root cause is gcu performance.
Increase dbus timeout.
Run end to end test.
> Increase dbus timeout for gcu

- azure-pipelines.yml
- gnmi_server/server_test.go
PR pipeline for 202311 branch is broken. Root cause is sonic-mgmt-common does not have 202311 branch, and we can't build sonic-gnmi with sonic-mgmt-common master branch.
Specify commit id for sonic-mgmt-common in pipeline.
Run pipeline for sonic-gnmi.
> Fix pipeline for 202311 branch

- azure-pipelines.yml
Allow partially succeeded builds when download artifacts in PR validation.
> [ci] Allow partially succeeded build when downloading.

- sonic_service_client/dbus_client.go
dbus timeout is not enough for some hwsku.
Increase dbus timeout to support all possible hwsku.
Run unit test and end2end test.
> Update all the dbus timeout

- .gitignore
Also clean them up with documentation.
This will prevent accidentally adding file to commit by "git add ." 
check git status for unwanted untracked file after executing build pipeline.
git status should show no untracked file after build pipeline.
> Add build artifacts to gitignore.

- .github/workflows/codeql-analysis.yml
CodeQL has been failing at head due to missing ../sonic-mgmt-common
Add checking out sonic-mgmt-common.
Run at my forked master: https://github.com/hdwhdw/sonic-gnmi/actions/runs/12385901251
The run on this PR pipeline uses the workflow file on its master, hence failing is expected.
> Fix CodeQL failure due to missing sonic-mgmt-common.

- gnmi_server/server_test.go
As part of dependency on google/gnxi, full path needs to be provided including target "COUNTERS_DB"
Added target to path
Pipeline
> Fix dependency from PR:345

- sonic_data_client/client_test.go
- sonic_data_client/json_client.go
- sonic_data_client/mixed_db_client.go
- test/test_gnmi_configdb_patch.py
Need to support incremental config for multi-asic device.
Update json client to support new checkpoint file.
Run gnmi unit test and end to end test.
> Update json client to support multi-asic
